//HintName: GrabberGen.g.cs

// <auto-generated />
namespace NodeGrabber
{
    public sealed class GrabAttribute : Attribute
    {
        public readonly string Path;
        public GrabAttribute(string path = null)
        {
            Path = path;
        }
    }
}
